Add document with the naming schema of builds
leapp-to/guidelines pull request #5
Opened 2018-12-21 14:52 UTC by pirat89

2019-01-02 13:27 UTC, vinzenz requested changes
small typo

2019-01-02 13:27 UTC, vinzenz commented on build-schema.md
> +- **short-hash** is shortened hash of the commit from which the build hase been
hase -> has

2019-01-02 17:25 UTC, pirat89 commented on build-schema.md
> +- **short-hash** is shortened hash of the commit from which the build hase been
Thanks :) Fixed.

2019-01-07 15:15 UTC, vinzenz approved these changes

2019-01-07 15:15 UTC, merged